config/routes.rb
require 'sidekiq/web'
# Sidekiq::Web.set :sessions, false

Rails.application.routes.draw do
  devise_for :users, path: "", controllers: {
    sessions: "sessions",
    login_codes: "login_codes"
  }
  authenticate :user, ->(u) { u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :svc, defaults: { format: :json } do
    resources :users
    resources :attachments

    resources :projects do
      scope module: 'projects' do
        resources :analytics do
          get 'issue_creator_chart', on: :collection
          get 'issue_activity_chart', on: :collection
        end
      end
    end

    devise_scope :user do
      post :deliver, to: "sessions#deliver"
      post :sign_in, to: "sessions#create"
      delete :sign_out, to: "sessions#destroy"
    end

    namespace :v2 do
      namespace :admin do
        resources :users
        resources :projects
      end

      resources :projects do
        scope module: 'projects' do
          resource :profile

          resources :roadmaps
          resources :storyboards do
            resources :scenes
            resources :requirements
          end

          resources :issues do
            member do
              post :merge
              patch :resolve
              patch :process, to: "issues#process2"
            end
            get :summary, on: :collection

            resources :issue_actions
            resource :body, controller: "issue_bodies" do
              member do
                patch :convert_comment
              end
            end
            resources :issue_relationships
            resources :issue_surveys

            resources :comments do
              member do
                get :comment
                patch :convert
              end
            end
            resource :subscription
          end
          resources :issue_migrations

          resources :members do
            patch :archive, on: :member
          end
          resources :categories
          resources :milestones do
            patch :archive, on: :member
            patch :active, on: :member
          end
          resources :issue_templates
          resources :test_case_labels
          resources :platforms

          resources :test_cases do
            get :history, on: :member
          end
          resources :test_case_stats

          resources :plans do
            resources :phases do
              resources :task_upshots
            end

            resources :tasks do
              member do
                patch :ignore
                patch :unignore
              end

              resources :upshots do
                member do
                  patch :state
                  patch :content
                end
              end
            end
          end
        end
      end

      namespace :profile do
        resource :account
        resources :issues
        resources :members
      end
    end
  end

  root to: "main#root"
  get "*path" => "main#root"
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < Api::BaseController
  before_action -> { @user = current_user }
  load_and_authorize_resource

  def index
    @projects_scope = @user.projects
    @projects_scope = @projects_scope.ransack(params[:q]).result
    @projects = @projects_scope.page(params[:page])

    kaminari_headers(@projects)
  end

  def show
  end

  def create
    @project.save
    respond_with @project
  end

  def update
    @project.update(project_params)
    respond_with @project
  end

  def destroy
    @project.archive
    respond_with @project
  end

protected

  def project_params
    params.permit(:name)
  end
end

app/controllers/projects/issue_forms_controller.rb
class Projects::IssueFormsController < BaseProjectController
  load_and_authorize_resource :project
  load_and_authorize_resource :issue
  load_and_authorize_resource through: :issue

  def index
  end

  def new
  end

  def create
    @issue_form.save
    respond_with @issue_form
  end

  def edit
  end

  def update
    @issue_form.assign_attributes(issue_form_params)
    @issue_form.submit_and_save
    respond_with @issue_form
  end

protected
  def issue_form_params
    params.fetch(:issue_form, {}).permit(*permit_attributes)
  end

  def permit_attributes
    result = [:template_id, :remark, inputs_attributes: [:template_input_id, :value]]
    result
  end
  helper_method :permit_attributes
end

app/controllers/projects/issue_infos_controller.rb
class Projects::IssueSurveiesController < BaseProjectController
  load_and_authorize_resource :project
  load_and_authorize_resource :issue
  load_and_authorize_resource through: :issue

  def index
  end

  def new
  end

  def create
    @issue_surveys.save
    respond_with @issue_surveys
  end

  def edit
  end

  def update
    @issue_surveys.assign_attributes(issue_survey_params)
    @issue_surveys.submit_and_save
    respond_with @issue_surveys
  end

  def destroy
    @issue_surveys.destroy
    respond_with @issue_surveys, location: ok_url_or_default([@project, @issue])
  end

protected
  def issue_survey_params
    params.fetch(:issue_survey, {}).permit(*permit_attributes)
  end

  def permit_attributes
    result = [:template_id, :remark, inputs_attributes: [:template_input_id, :value]]
    result
  end
  helper_method :permit_attributes
end

app/controllers/projects/versionables_controller.rb
class Projects::VersionablesController < BaseProjectController
  load_and_authorize_resource :project
  load_and_authorize_resource :test_case, through: :project
  load_and_authorize_resource through: :test_case

  def new
    @versionable.history_id = params[:history_id]
    @versionable.category = params[:category]
  end

  def create
    @versionable.save
    respond_with @versionable, location: ok_url_or_default([@project, @test_case])
  end

  def edit
  end

  def update
    @versionable.update(versionable_params)
    respond_with @versionable, location: ok_url_or_default([@project, @test_case])
  end

  def destroy
    @versionable.destroy
    respond_with @versionable, location: ok_url_or_default([@project, TestCase])
  end

protected
  def versionable_params
    params.fetch(:versionable, {}).permit(:test_case_version_id, :category, :history_id)
  end
end

app/controllers/svc/projects/analytics_controller.rb
class Svc::Projects::AnalyticsController < Svc::Projects::BaseController
  before_action -> { @project = current_project }

  def show
  end

  def issue_creator_chart
    @issue_creator_chart = IssueCreatorChart.new(issue_creator_chart_params)
  end

  def issue_activity_chart
    @issue_activity_chart = IssueActivityChart.new(issue_activity_chart_params)
  end

protected
  def issue_creator_chart_params
    params.permit(:project_id, :starts_on, :ends_on, :role).merge(project_id: @project.id)
  end

  def issue_activity_chart_params
    params.permit(:project_id, :starts_on, :ends_on, :role).merge(project_id: @project.id)
  end
end

app/controllers/svc/projects/base_controller.rb
class Svc::Projects::BaseController < Svc::BaseController

protected
  def current_project
    @project ||= Project.find(params[:project_id])
  end

  def current_member
    return @current_member if defined?(@current_member)
    @current_member = current_project.members.where(user_id: current_user).take
  end

  def current_ability
    super.tap { |a| a.apply_member_permissions(current_member) }
  end
end

app/controllers/svc/v2/admin/projects_controller.rb
class Svc::V2::Admin::ProjectsController < Svc::BaseController
  before_action -> { authorize! :manage, :admin }
  load_and_authorize_resource

  def index
    @projects_scope = @projects
    @projects_scope = @projects_scope.ransack(params[:q]).result
    @projects = @projects_scope.page(params[:page]).per(params[:limit])
  end

  def show
  end

  def create
    @project.save
    respond_with @project
  end

  def update
    @project.update(project_params)
    respond_with @project
  end

  def destroy
    @project.archive
    respond_with @project
  end

protected

  def project_params
    params.permit(:name, :trello_list_id, :trello_api_key, :trello_api_token, :webhook_url)
  end
end

app/controllers/svc/v2/projects/base_controller.rb
class Svc::V2::Projects::BaseController < Svc::BaseController

  protected
    def current_project
      @project ||= Project.find(params[:project_id])
    end

    def current_member
      return @current_member if defined?(@current_member)
      @current_member = current_project.members.where(user_id: current_user).take
    end

    def current_ability
      super.tap { |a| a.apply_member_permissions(current_member) }
    end
  end

app/controllers/svc/v2/projects/categories_controller.rb
class Svc::V2::Projects::CategoriesController < Svc::V2::Projects::BaseController
  before_action -> { @project = current_project }
  load_and_authorize_resource through: :project

  def index
    @categories

    if resource_graph_columns.include?("counts")
      @issues_counts = @project.issues.group(:category_id).count
    end
  end

  def create
    @category.save
    respond_with @category
  end

  def show
  end

  def update
    @category.update(category_params)
    respond_with @category
  end

  def destroy
    @category.destroy
    respond_with @category
  end

protected
  def category_params
    params.permit(:name, :description, :color)
  end
end

app/controllers/svc/v2/projects/comments_controller.rb
class Svc::V2::Projects::CommentsController < Svc::V2::Projects::BaseController
  before_action -> { @project = current_project }
  load_and_authorize_resource :issue, with_scope: ->(base) {
    params[:action] == "index" ? base.in_project(@project) : base.where(project_id: @project.id)
  }
  load_and_authorize_resource through: :issue

  def index
    @comments = @comments.joins(:member).where(members: { project_id: current_member.project_id })
  end

  def create
    @comment.member = current_member
    if @comment.save
      @issue.notify_commented_by(current_member)
    end
    respond_with @comment
  end

  def update
    @comment.update_with_author(comment_params, current_member)
    respond_with @comment
  end

  def convert
    @comment.convert(convert_params)
    respond_with @comment
  end

  def destroy
    @comment.destroy
    respond_with @comment
  end

protected
  def comment_params
    params.permit(:content, :comment_id, :display, attachments_params: [ :id, :title ])
  end

  def convert_params
    params.permit(:comment_id)
  end
end

app/controllers/svc/v2/projects/issue_actions_controller.rb
class Svc::V2::Projects::IssueActionsController < Svc::V2::Projects::BaseController
  before_action -> { @project = current_project }
  load_and_authorize_resource :issue, through: :project

  def create
    authorize! :update, @issue

    with_email_notification do
      @activities = @issue.update_with_author(issue_params, current_member)
      IssueNotifyJob.perform_later(@issue.id)
    end

    respond_with @issue
  end

protected
  def issue_params
    params.permit(:title, :state, :priority, :creator_id, :assignee_id, :milestone_id, :category_id)
  end

  def with_email_notification
    yield
    if (changes = @issue.previous_changes).any?
      @issue.notify_creator if changes.fetch("state", []).last == "resolved"
      current_user.subscribe(@issue)
      @issue.notify_changed_by(current_member, changes)
    end
  end
end

app/controllers/svc/v2/projects/issue_bodies_controller.rb
class Svc::V2::Projects::IssueBodiesController < Svc::V2::Projects::BaseController
  before_action -> { @project = current_project }
  load_resource :issue, through: :project

  def update
    authorize! :update, 'IssueBody'

    with_email_notification do
      @issue.update_with_author(body_params, current_member)
    end

    respond_with @issue
  end

  def convert_comment
    authorize! :update, 'IssueBody'

    @issue.convert_comment
  end

protected

  def body_params
    params.permit(:content, attachments_params: [ :id, :title ])
  end

  def with_email_notification
    yield
    if (changes = @issue.previous_changes).any?
      @issue.notify_creator if changes.fetch("state", []).last == "resolved"
      current_user.subscribe(@issue)
      @issue.notify_changed_by(current_member, changes)
    end
  end
end

app/controllers/svc/v2/projects/issue_migrations_controller.rb
class Svc::V2::Projects::IssueMigrationsController < Svc::V2::Projects::BaseController
  before_action -> { @project = current_project }

  def create
    @form = IssueMigrationForm.new(migrate_params)
    @form.submit(current_member) do |source_member, target_member|
      source_ability = Ability.new(current_user) { |it| it.apply_member_permissions(source_member) }
      source_ability.authorize! :manage, Issue

      target_ability = Ability.new(current_user) { |it| it.apply_member_permissions(target_member) }
      target_ability.authorize! :manage, Issue
    end

    respond_with @form
  end

protected
  def migrate_params
    params.permit(:source_issue_id, :target_project_id, :target_category_id)
  end
end

app/controllers/svc/v2/projects/issue_relationships_controller.rb
class Svc::V2::Projects::IssueRelationshipsController < Svc::V2::Projects::BaseController
  load_and_authorize_resource :project
  load_and_authorize_resource :issue, through: :project
  load_and_authorize_resource through: :issue, through_association: :source_relationships, parent: false

  def create
    @issue_relationship.submit_and_save(current_member)
    respond_with @issue_relationship
  end

  def destroy
    @issue_relationship.destroy
    respond_with @issue_relationship
  end

protected
  def issue_relationship_params
    params.permit(:target_id, :creator_subscribe_target_issue)
  end
end

app/controllers/svc/v2/projects/issue_surveys_controller.rb
class Svc::V2::Projects::IssueSurveysController < Svc::V2::Projects::BaseController
  load_and_authorize_resource :project
  load_and_authorize_resource :issue
  load_and_authorize_resource through: :issue

  def index
    @issue_surveys = @issue.issue_surveys.ranked
  end

  def create
    @issue_survey.save
    respond_with @issue_survey
  end

  def update
    @issue_survey.assign_attributes(issue_survey_params)
    @issue_survey.submit_and_save
    respond_with @issue_survey
  end

  def destroy
    @issue_survey.destroy
    respond_with @issue_survey
  end

protected
  def issue_survey_params
    params.permit(*permit_attributes)
  end

  def permit_attributes
    result = [:template_id, :remark, inputs_attributes: [:template_input_id, :value]]
    result
  end
  helper_method :permit_attributes
end

app/controllers/svc/v2/projects/issue_templates_controller.rb
class Svc::V2::Projects::IssueTemplatesController < Svc::V2::Projects::BaseController
  before_action -> { @project = current_project }
  load_and_authorize_resource through: :project

  def index
    @issue_templates = @issue_templates.includes(:default_category).references(:default_category)
  end

  def create
    @issue_template.save
    respond_with @issue_template
  end

  def show
    respond_with @issue_template
  end

  def update
    @issue_template.update(issue_template_params)
    respond_with @issue_template
  end

  def destroy
    @issue_template.destroy
    respond_with @issue_template
  end

protected
  def issue_template_params
    params.permit(*permit_attributes)
  end

  def permit_attributes
    result = [
      :name, :lookup_by_build_form, :title_suggestion, :content_suggestion,
      :default_category_id, :default_priority,
      inputs_attributes: [:id, :order_index, :label, :_destroy]
    ]
    result
  end
  helper_method :permit_attributes
end

app/controllers/svc/v2/projects/members_controller.rb
class Svc::V2::Projects::MembersController < Svc::V2::Projects::BaseController
  before_action -> { @project = current_project }
  load_and_authorize_resource through: :project

  def index
    @q = @members.ransack(params[:q])
    @q.sorts = "user_email" if @q.sorts.empty?
    @members = @q.result
  end

  def show
  end

  def create
    @member.submit_and_save
    respond_with @member
  end

  def update
    @member.update(member_params)
    respond_with @member
  end

  def destroy
    @member.destroy
    respond_with @member
  end

  def archive
    @member.archive
    respond_with @member
  end

protected
  def member_params
    params.permit(:role, :user_email, :nickname, :receive_mail)
  end

  def flash_interpolation_options
    { reason: @member.errors.full_messages.first }
  end
end

app/views/projects/tasks/change_state.xhrml.erb
<div class="modal-header">
  <h5 class="modal-title"><%= @task.finished? ? @task.test_case_when_finishing.title : @task.test_case.title %></h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <% if @task.finished? && @task.changed_after_finish? %>
        <div class="alert alert-danger">当前查看的为历史版本，本案例在完成测试后又发生了更改</div>
      <% end %>
      <% if (content = @task.test_case_when_finishing.content) %>
        <div class="alert alert-info"><%= content %></div>
      <% end %>
      <p><%=h Task, :state %>: <%= @task.state.text %></p>
      <% if @task.state == "failure" %>
        <p><%= h Task, :message %>: </p>
        <%= render "shared/page_content.html.erb", content: @task.message %>
        <%= render "shared/attachments_box.html.erb", attachmentable: @task %>
      <% end %>
    </div>
  </div>
</div>
<div class="modal-footer">
  <div class="mr-auto">
    <% if @task.issue_id.nil? %>
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= action_i18n('relate') %>
        </button>
        <div class="dropdown-menu">
          <% @related_issues.each do |issue| %>
            <%= link_to "#{h(Task, :issue_id)} #{}: #{issue.id}", [@project, @plan, @task, task: { issue_id: issue.id }], method: :patch, class: "dropdown-item small" %>
          <% end %>
          <%= link_to action_i18n('more'), project_issues_url(@project, { q: { state_filter: "opening" }, related_task: @task.id }), class: "dropdown-item small" %>
        </div>
      </div>
    <% else %>
      <div class="btn-group">
        <%= link_to "#{h(Task, :issue_id)} #{}: #{@task.issue_id}", project_issue_path(@project, @task.issue_id), class: "btn btn-primary" %>
        <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to action_i18n('cancel_relate'), [@project, @plan, @task, task: { issue_id: nil }], method: :patch, class: "dropdown-item small text-muted" %>
        </div>
      </div>
    <% end %>
  </div>
  <% data = { remote: true, target: "#uploadAttachmentsModal", type: :xhrml } %>
  <%= link_to Task.state.find_value(:pass).text, [@project, @plan, @task, task: { state: :pass, test_case_version: DateTime.now }], method: :patch,
              class: "btn btn-success", data: { remote: true, type: :xhrml, target: ".modal-content" } %>
  <%= link_to Task.state.find_value(:failure).text, upload_attachment_project_plan_task_path(@project, @plan, @task), data: data, class: "btn btn-danger" %>

</div>

app/views/projects/tasks/relate.html.erb
<div class="page-header">
  <h2><%= page_i18n :index, model_name: h(Issue) %></h2>
  <div class="actions ml-auto">
    <%= new_link Issue, [:new, @project, @task, :issue, request_for_ok_url] if can? :create, Issue %>
  </div>
</div>

<%= backend_search_form_for @q, url: relate_project_plan_task_path(@project, @plan, @task) do |f| %>
  <%= f.input :title_cont, label: false, placeholder: "search...." %>
  <%= f.submit class: "btn btn-outline-success mb-2" %>
<% end %>

<table class="table">
  <colgroup>
    <col width="40%">
    <col width="20%">
    <col width="20%">
    <col width="10%">
    <col>
  </colgroup>
  <tr>
    <th><%=h Issue, :title %></th>
    <th><%=h Issue, :state %></th>
    <th><%=h Issue, :label_ids %></th>
    <th><%=h Issue, :milestone_id %></th>
    <th><%= page_i18n :actions %></th>
  </tr>
  </thead>
  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td>
          <%= link_to issue.title, [@project, issue] %>
        </td>
        <td>
          <span class="<%= issue_state_class_name(issue.state, :text) %>">
          <%= issue.state.text %>
          </span>
        </td>
        <td>
          <% issue.labels.each do |label| %>
            <%= label_tag(label, label.name) %>
          <% end %>
        </td>
        <td>
          <% if issue.milestone %>
            <%= issue.milestone.title %>
          <% end %>
        </td>
        <td>
          <%= link_to action_i18n(:relate), [@project, @plan, @task, task: { issue_id: issue.id }], method: :patch %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<nav class="table-pagination">
  <%= paginate @issues %>
</nav>