config/routes.rb
require 'sidekiq/web'
# Sidekiq::Web.set :sessions, false

Rails.application.routes.draw do
  devise_for :users, path: "", controllers: {
    sessions: "sessions",
    login_codes: "login_codes"
  }
  authenticate :user, ->(u) { u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :svc, defaults: { format: :json } do
    resources :users
    resources :attachments

    resources :projects do
      scope module: 'projects' do
        resources :analytics do
          get 'issue_creator_chart', on: :collection
          get 'issue_activity_chart', on: :collection
        end
      end
    end

    devise_scope :user do
      post :deliver, to: "sessions#deliver"
      post :sign_in, to: "sessions#create"
      delete :sign_out, to: "sessions#destroy"
    end

    namespace :v2 do
      namespace :admin do
        resources :users
        resources :projects
      end

      resources :projects do
        scope module: 'projects' do
          resource :profile

          resources :roadmaps
          resources :storyboards do
            resources :scenes
            resources :requirements
          end

          resources :issues do
            member do
              post :merge
              patch :resolve
              patch :process, to: "issues#process2"
            end
            get :summary, on: :collection

            resources :issue_actions
            resource :body, controller: "issue_bodies" do
              member do
                patch :convert_comment
              end
            end
            resources :issue_relationships
            resources :issue_surveys

            resources :comments do
              member do
                get :comment
                patch :convert
              end
            end
            resource :subscription
          end
          resources :issue_migrations

          resources :members do
            patch :archive, on: :member
          end
          resources :categories
          resources :milestones do
            patch :archive, on: :member
            patch :active, on: :member
          end
          resources :issue_templates
          resources :test_case_labels
          resources :platforms

          resources :test_cases do
            get :history, on: :member
          end
          resources :test_case_stats

          resources :plans do
            resources :phases do
              resources :task_upshots
            end

            resources :tasks do
              member do
                patch :ignore
                patch :unignore
              end

              resources :upshots do
                member do
                  patch :state
                  patch :content
                end
              end
            end
          end
        end
      end

      namespace :profile do
        resource :account
        resources :issues
        resources :members
      end
    end
  end

  root to: "main#root"
  get "*path" => "main#root"
end

app/models/attachment.rb
# == Schema Information
#
# Table name: attachments
#
#  id                  :bigint           not null, primary key
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  title               :text
#  attachmentable_id   :bigint
#  attachmentable_type :string
#  content_type        :string
#

class Attachment < ApplicationRecord
  belongs_to :attachmentable, polymorphic: true, optional: true
  has_one_attached :file

  validates :title, presence: true, length: { maximum: 20 }, on: :update, if: -> { will_save_change_to_title? }

  before_create :assign_title, :assign_content_type

  def assign_title
    self.title = self.file.blob.filename
  end

  def assign_content_type
    self.content_type = self.file.blob.content_type
  end

  def image?
    file.image?
  end

  def video?
    file.video? && content_type.include?('mp4')
  end
end

app/controllers/svc/attachments_controller.rb
class Svc::AttachmentsController < Svc::BaseController
  load_and_authorize_resource

  def create
    @attachment.save
    @blob = ActiveStorage::Blob.find(@attachment.file.attachment.blob_id)
    respond_with @attachment
  end

  def update
    authorize! :update, @attachment.attachmentable

    @attachment.update(attachment_params)
    respond_with @attachment
  end

  def destroy
    authorize! :update, @attachment.attachmentable

    @attachment.destroy
  end

protected
  def attachment_params
    params.permit(:file, :title)
  end
end

app/views/attachments/_form.html.erb
<% file = attachment.file %>
<% blob = ActiveStorage::Blob.find(file.attachment.blob_id) %>
<div class="media border bg-light p-2 align-items-center">
  <div class="mr-2" style="width: 3rem">
    <div class="embed-responsive embed-responsive-1by1">
      <div class="embed-responsive-item embed-responsive-item d-flex align-items-center justify-content-center">
        <% if blob.content_type.split('/')[0] == 'image' %>
          <%= image_tag url_for(file), class: "h-100" %>
        <% else %>
          <%= image_tag 'file.png', class: "h-100" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="media-body d-flex flex-column">
    <div class="d-flex justify-content-between align-items-center">
      <h4 class="mb-0"><%= blob.filename.to_s %></h4>
      <%= link_to(content_tag(:i, '',class: 'fa fa-pencil-square-o'), edit_attachment_path(attachment))%>
    </div>
    <div class="small">
      <span class="text-secondary mr-1"><%= number_to_human_size(blob.byte_size, precision: 2, locale: 'en') %></span>
      <%= link_to polymorphic_url(file), class: "clipboard" do %>
        <span class="fa fa-link text-muted small"></span>
      <% end %>
    </div>
  </div>
</div>